[package]
name = "testcrate"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lute-src-rs = { path = ".." }
lute-prebuilts-chooser = { git = "https://github.com/mluau/lute-prebuilts-chooser", optional = true }

[features]
prebuilt = ["dep:lute-prebuilts-chooser"]